[package]
name = "rust-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
sqlx = { version = "0.6.3", features = ["postgres", "runtime-tokio-rustls"] }
futures = "0.3"
