version: '3.9'
  
services:
  postgres:
    image: postgres
    container_name: "sqlxlrn"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres:
    name: ${DB_VOL_NAME}
